version: '3'
services:
  app:
    container_name: nest-backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    env_file:
      - .env.docker
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=assessment
